### ISSUE TITLE
[Issue]: Rock App does not allow Phone/Email login if the Profile Protection level is High or Extreme.

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock.Mobile-Issues#7] opened 2022-10-14 20:01 UTC
### Describe the Issue in Detail

Submitted on behalf of Fellowship Bible Church of Northwest Arkansas

In using the Rock Mobile App, people with a profile protection level of high or extreme (such as church staff) cannot login to the app using Phone Number or Email.  They receive a message "It appears you have an account in our system that has security access which requires you to login with a username and password."  However, they use Office 365 logins for Rock so they do not have database logins that can be used on the app and the app has no way to change the password if a new login is created (which is not secure).

 Even if the profile protection is lowered on staff security groups, the job sets them to High if they have scheduled giving or stored payment methods.

### Can reproduce in

- [ ] Orange App
- [ ] Blue App

### Steps to Reproduce

1. Create a person in the Rock DB with an Extreme Profile Protection level and a mobile phone and email.
2. Load the app on the phone with the entered number.
3. Try to login using phone or email.
4. "It appears you have an account in our system that has security access which requires you to login with a username and password." is displayed.

### Expected Behavior

I would expect phone/email code authentication to be able to be used on the app even with profile protection in place.  This seems as close to MFA as is available at present and more secure than having separate logins just for the Mobile App (separate from Office 365 used for Rock).

### Actual Behavior

Phone and email based authentication is not available to staff members. 

### Screenshots or Videos

![AppLogin](https://user-images.githubusercontent.com/33356643/195931846-52f86f00-57d6-483d-bd61-f9a6c2c70a2a.jpg)

### Mobile Shell Version

1.4.0.8

### Last Known Working Version

Prior to v13.6 Rock Server Upgrade

### iOS Device Type(s) and iOS Version(s)

iPhone 12

### Android Device Type(s) and Android Version(s)

N/A

**Comment by bobrufenacht** [comment] 2022-10-14 20:06
This was on the Blue App.  I think I missed that checkbox.

**Comment by BemaDavidBensen** [comment] 2022-10-20 16:23
@mikejed What is the best way to verify a bug for mobile?

**Comment by bradencohen** [comment] 2023-01-10 23:11
Closing as a duplicate of: https://github.com/SparkDevNetwork/Rock/issues/5199, since that issue received a response already.

**Closed by bradencohen** 2023-01-10 23:11 UTC
Labels: bug, unverified
