### ISSUE TITLE
[Issue]: Android Devices Skip-Play Video using HLS Links

### ISSUE THREAD

**Issue by melissadrexler** [SparkDevNetwork/Rock.Mobile-Issues#10] opened 2023-04-11 21:20 UTC
### Describe the Issue in Detail

We use HLS links from Vimeo to play our messages in the app. However, the videos are skipping in audio/video for Android devices, while iOS devices play the content correctly.

### Can reproduce in

- [X] Orange App
- [ ] Blue App

### Steps to Reproduce

1. Use the Rock:MediaPlayer on an Android device
2. Send an HLS link to it 
3. View the video

### Expected Behavior

Video plays without skipping in the audio or video.

### Actual Behavior

The video skips every few seconds for audio/video.

### Screenshots or Videos

https://drive.google.com/file/d/1_9FjW6j2wYxPOpL9nOPf2FqKMCpnKjE5/view?usp=share_link

(Sorry it is a video of a phone, but I needed the audio and the video)

### Reproduction XAML

```xml
{% assign ItemId = PageParameter.Item | AsInteger %}
{% assign audioLink = Item | Attribute:'AudioLink','RawValue' %}
{% assign itemImage = Item | Attribute:'MessageImage','RawValue' %}

{% if itemImage and itemImage != '' %}
    {% assign imgLink = 'Global' | Attribute:'PublicApplicationRoot' | Append:'GetImage.ashx?Guid=' | Append:itemImage %}
{% endif %}

{% assign videoId = Item | Attribute:'VideoLink' | Trim  %}
{% assign HSLLink = Item | Attribute:'HLSLink','RawValue' | Trim  %}
{% assign tenEightyFile = Item | Attribute:'1080p' | Trim  %}
{% assign sevenTwentyFile = Item | Attribute:'720p' | Trim  %}
{% assign threeSixtyFile = Item | Attribute:'360p' | Trim  %}

{% if HSLLink != '' %}
    {% assign vidUrl = HSLLink %}
    {% comment %} HSL video does not play nicely with a thumbnail, so reset the image link {% endcomment %}
    {% assign imgLink = '' %}
{% else %}
    {%- webrequest url:'https://player.vimeo.com/video/{{ videoId }}/config' -%}
        {%- assign jsonObject = results -%}
        {%- assign vidThumb = jsonObject.video.thumbs.960 -%}
        {%- for p in jsonObject.request.files.progressive -%}
            {% if p.height == 720 %}
                {% assign vidUrl = p.url %}
            {% elseif p.height == 1080 %}
                {% assign vidUrl = p.url %}
            {% elseif p.height == 360 %}
                {% assign vidUrl = p.url %}
            {% endif %}
        {%- endfor -%}
    {%- endwebrequest -%}
{% endif %}

<StackLayout>
    {% if vidUrl != '' %}
        <Rock:MediaPlayer AutoPlay="False"
                {% if imgLink and imgLink != '' %}ThumbnailSource="{{ imgLink }}"{% endif %}
                PlayButtonSource="https://admin.itownchurch.com/Content/ExternalSite/Mobile/PlayButton.png"
                Source="{{ vidUrl | Escape }}"/>
    {% else %}
    {% endif %}
</StackLayout>
```

### Mobile Shell Version

v4

### iOS Device Type(s) and iOS Version(s)

NA

### Android Device Type(s) and Android Version(s)

Pixel 5a running Android 11 2. Motorola running Android 12.

**Comment by Tibincrunch** [comment] 2023-04-11 21:49
@melissadrexler thanks for the report and video! Would you be able to provide an HLS URL or two that we can test against?

**Comment by melissadrexler** [comment] 2023-04-12 13:37
@Tibincrunch Sure thing! Here are our latest two messages:
https://player.vimeo.com/external/816102844.m3u8?s=c8b44c8729e919f62729a585a79ad2f165eedc8d
https://player.vimeo.com/external/814083821.m3u8?s=e0a40a2b81db25f788da8eba0badf0fcc17bb92c

**Comment by bscottdavis** [comment] 2023-06-02 22:44
If it helps at all we are seeing something similar in our App. Let me know if there is anything I can send over to help with troubleshooting. Thanks as always for you help.

**Comment by Tibincrunch** [comment] 2023-06-14 17:24
I was able to reproduce this issue on our Android devices and have added this to our internal board. Thank you for the report and your patience; we'll follow up when we know more.

**Comment by bradencohen** [comment] 2023-06-20 21:40
Hey everyone, just to post some updates here:

We have ruled out quite a few things through testing, and are actively continuing to debug and research the cause of the poor Media Player performance on Android (specifically for HLS links). This is something we _definitely_ want to support in a clean and seamless fashion, so I'll do my best to keep everyone updated here.

**Comment by bradencohen** [comment] 2023-11-01 22:37
Coming back to drop some updates:

With V5 officially released (woohoo), this is one of the forefront fixes for V6 and .NET MAUI. There has been lots of testing/research into our different Media Player options and I think we'll be able to improve the experience altogether (along with fixing this bug).

**Comment by bradencohen** [comment] 2023-12-18 17:49
This has been fixed in shell v6, which will be released in .NET MAUI. More info on getting to this version coming soon.

**Closed as completed by bradencohen** 2023-12-18 17:49 UTC
Labels: type: bug
